apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.microservice.name }}
  name: {{ .Values.microservice.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        io.kompose.service: {{ .Values.microservice.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.containerPull.pullSecret }}    
      containers:
        - env:
            {{- include "ai-platform.common-environment-values" . | nindent 12 }}
            - name: LLM_URL
              value: "http://172.16.20.175:8000/v1"
            - name: MCP_GLARUS_SERVER
              value: "http://172.16.20.40:30903"                      
          image: {{ .Values.containerPull.registry }}/{{ .Values.microservice.name }}:{{ .Values.containerPull.imageTag }}
          name: {{ .Values.microservice.name }} 
          ports:
            {{- if eq .Values.microservice.name "mcp-server" }}
            - containerPort: 9003
            {{- else if eq .Values.microservice.name "mcp-service" }}
            - containerPort: 9001
            {{- else if eq .Values.microservice.name "orchestrator" }}
            - containerPort: 9080
            {{- end }}         
      restartPolicy: Always

