{{- if eq .Values.microservice.name "mcp-server" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.microservice.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /mcp(*)
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.microservice.name }}
                port:
                  number: 9003
{{- end }}
