variables:
  SERVICES: '["mcp-server", "mcp-service", "orchestrator"]' #Так будут называться микросервисы,и ДИРЕКТОРИИ в которых они лежат.

  GIT_SSL_NO_VERIFY: "true" 
  DOCKER_BUILDKIT: 1

stages:
  - trigger
  - pre build
  - build
  - deploy

modify:template:
  stage: trigger
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod" || $CI_COMMIT_BRANCH == "stable"'
      changes:
           - services/**/*
  script:
    - envsubst '${SERVICES}' < template.yml > template.gitlab-ci.yml
  artifacts:
    paths:
      - template.gitlab-ci.yml

trigger:template:
  stage: trigger
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "prod" || $CI_COMMIT_BRANCH == "stable"'
      changes:
           - services/**/*
  trigger:
    include: 
      - artifact: template.gitlab-ci.yml
        job: modify:template
    forward:
      pipeline_variables: true
  needs:
    - job: modify:template



